name: Build and Push image to Docker Hub

# Controls when the workflow will run
on: workflow_dispatch

env:
  TAG: ${{ github.sha }}
  IMAGE_NAME: oafunctioncontainer
  DOCKER_ACCOUNT: oaviles
  

jobs:
  login:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
           
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ env.DOCKER_ACCOUNT }}/${{ env.IMAGE_NAME }}:${{ env.TAG }}
          
        
